### ISSUE TITLE
Unable to use with Leaflet.groupedlayercontrol

### ISSUE THREAD

**Issue by growe19** [jieter/Leaflet.Sync#33]
I don't seem to be able to get this to work whilst also wanting to use the Leaflet.groupedlayercontrol.

**Comment by jieter** [comment]
@growe19 Sorry to reply this late. Is this still relevant? If it is, please show a playground-leaflet or jsfiddle which demonstrates the problem.

**Comment by jieter** [comment]
closed for lack of detail.
