### ISSUE TITLE
Github pages out of date

### ISSUE THREAD

**Issue by jjimenezshaw** [jieter/Leaflet.Sync#36]
Hi.
I have seen that gh-pages is not up to date (like [turban.github.io/Leaflet.Sync/examples/multiple.html](http://turban.github.io/Leaflet.Sync/examples/multiple.html) ). Could you please update it or even better, change the setting to use master branch as source of Github Pages? Then the examples folder would be accesible on master. 
Thanks

**Comment by jieter** [comment]
Yes it is, I'll repush to gh-pages after the current PRs are merged.

I'm not the admin for this repo, maybe @turban can set the github pages branch to master?

**Comment by turban** [comment]
I'm trying to transfer the ownership to you @jieter, but you already have a fork at https://github.com/jieter/Leaflet.Sync - can it be deleted?

**Comment by jieter** [comment]
@turban just deleted the repo jieter/Leaflet.Sync. Thanks!

**Comment by turban** [comment]
Ownership transferred @jieter - thanks for looking after this repo! :-)

**Comment by jieter** [comment]
Just set master as the github pages branch and deleted gh-pages.
