### ISSUE TITLE
zoomend event fired twice

### ISSUE THREAD

**Issue by Fjnova** [jieter/Leaflet.Sync#49]
This is modified code of dual.html
I am trying to trigger event when map changed viewport by zoomend & dragend event. But unfortunately I received zoomend event fired twice

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Leaflet Sync Demo</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet-src.js" crossorigin=""></script>

    <style type="text/css">
        html, body { width: 100%; height: 100%; margin: 0; }
        #map1, #map2 { width: 49.5%; height: 100%; }
        #map1 { float: left; }
        #map2 { float: right; }
    </style>
</head>

<body>
    <div id="map1" class="map1"></div>
    <div id="map2" class="map2"></div>
    <script src="../L.Map.Sync.js"></script>

    <script type="text/javascript">
        var center = [59.336, 5.967];

        var layer1 = L.tileLayer('http://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=norges_grunnkart&zoom={z}&x={x}&y={y}');

        var layer2 = L.tileLayer('http://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo2&zoom={z}&x={x}&y={y}', {
            attribution: '© Kartverket'
        });

        var map1 = L.map('map1', {
            layers: [layer1],
            center: center,
            zoom: 14
        });

        map1.attributionControl.setPrefix('');

        var map2 = L.map('map2', {
            layers: [layer2],
            center: center,
            zoom: 14,
            zoomControl: false
        });

        map1.sync(map2);
        map2.sync(map1);
		
		var afterMapChangedPosition = function(e) {
			console.error(`afterMapChangedPosition: type: ${e.type}    --- ${e.target._container.className} `);
		}
		
		map1.on('zoomend', afterMapChangedPosition.bind(this));
		map1.on('dragend', afterMapChangedPosition.bind(this));
		map2.on('zoomend', afterMapChangedPosition.bind(this));
		map2.on('dragend', afterMapChangedPosition.bind(this));

    </script>
</body>
</html>

**Comment by yezhanpeng201314** [comment]
I meet same problems，can you tell me how to resolve this

**Comment by jjimenezshaw** [comment]
I guess it is because you get for both maps, map1 and map2.
By the way, the code you pasted does not work. There is missing code and typos.

**Comment by jjimenezshaw** [comment]
@jieter Do you want to close this issue?
