### ISSUE TITLE
Demo problem

### ISSUE THREAD

**Issue by valerio-bozzolan** [jieter/Leaflet.Sync#65]
Hi all! :)

I noticed some problems in the demo in HTTPs:

* https://thematicmapping.org/playground/leaflet/Leaflet.Sync/example.html

Is it known? :) Also in HTTP the right tileserver it seems not available.

Thank you so much!

**Comment by jjimenezshaw** [comment]
I would say that this is a problem at http://thematicmapping.org That example is very old. The examples in this repo are updated https://jieter.github.io/Leaflet.Sync/examples/dual.html

**Comment by valerio-bozzolan** [comment]
Thank you! That's awesome!
